In [3]:
import psycopg2
import pandas as pd
def read_query_function(query):
    connection_string='postgres://Test:bQNxVzJL4g6u@ep-noisy-flower-846766-pooler.us-east-2.aws.neon.tech/Globox'
    conn = psycopg2.connect(connection_string)
    data_frame = pd.read_sql_query(query,conn)
    conn.close()
    return data_frame

In [3]:
query1 = '''SELECT
  distinct u.id AS user_id,
  u.country,
  u.gender,
  g.group AS test_group,
  g.device,
 SUM(COALESCE(a.spent, 0)) AS total_spent
 FROM users u
 LEFT JOIN groups g ON u.id = g.uid
 LEFT JOIN activity a ON u.id = a.uid
 GROUP BY u.id, u.country, u.gender, g.group,g.device'''
read_query_function(query1)

<ipython-input-2-c09e6a76bd12>:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_frame = pd.read_sql_query(query,conn)

       user_id country gender test_group device  total_spent
0      1025507     GBR      M          B      I          0.0
1      1049407     USA   None          B      I          0.0
2      1033321     BRA      F          A      I          0.0
3      1033494     BRA      F          A      A          0.0
4      1013857     MEX   None          B      A          0.0
...        ...     ...    ...        ...    ...          ...
48938  1042793     USA      F          B      I          0.0
48939  1020206     BRA      M          B      I          0.0
48940  1045627     BRA   None          A      I          0.0
48941  1026969     USA      F          B      A          0.0
48942  1005995     DEU      F          B      A          0.0

[48943 rows x 6 columns]

In [4]:
query2='''
-- Select users
SELECT *
FROM users

JOIN activity
ON users.id = activity.uid
-- join 'users' and  'groups' with matching user IDs
JOIN groups
ON users.id= groups.uid
'''
read_query_function(query2)

<ipython-input-2-c09e6a76bd12>:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_frame = pd.read_sql_query(query,conn)

,id,country,gender,uid,dt,device,spent,uid,group,join_dt,device
0,1000039,GBR,F,1000039,2023-02-04,A,36.650000,1000039,B,2023-02-04,A
1,1000045,USA,F,1000045,2023-01-30,I,51.580000,1000045,B,2023-01-26,I
2,1000071,USA,F,1000071,2023-02-02,I,6.710000,1000071,B,2023-01-31,I
3,1000101,MEX,F,1000101,2023-02-05,A,5.674497,1000101,B,2023-02-02,A
4,1000101,MEX,F,1000101,2023-02-02,A,18.130000,1000101,B,2023-02-02,A
...,...,...,...,...,...,...,...,...,...,...,...
2228,1049880,TUR,M,1049880,2023-01-26,I,186.690000,1049880,A,2023-01-26,I
2229,1049891,BRA,F,1049891,2023-01-26,A,47.140000,1049891,B,2023-01-26,A
2230,1049894,BRA,F,1049894,2023-01-25,I,34.050000,1049894,A,2023-01-25,I
2231,1049927,AUS,F,1049927,2023-01-25,A,52.030000,1049927,A,2023-01-25,A
2232,1049973,MEX,F,1049973,2023-01-31,A,85.930000,1049973,B,2023-01-27,A

In [5]:
# query 3
query3='''SELECT activity.uid, COUNT(*) AS buy_onces
FROM activity
GROUP BY activity.uid
HAVING COUNT(*) < 2;'''
read_query_function(query3)

<ipython-input-2-c09e6a76bd12>:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_frame = pd.read_sql_query(query,conn)

          uid  buy_onces
0     1045330          1
1     1042972          1
2     1002751          1
3     1038060          1
4     1045788          1
...       ...        ...
1950  1019110          1
1951  1009293          1
1952  1045080          1
1953  1037474          1
1954  1012339          1

[1955 rows x 2 columns]

In [6]:
# query 4
query4='''SELECT *
FROM users
iNNER JOIN activity
ON users.id = activity.uid;'''
read_query_function(query4)

<ipython-input-2-c09e6a76bd12>:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_frame = pd.read_sql_query(query,conn)

           id country gender      uid          dt device       spent
0     1000039     GBR      F  1000039  2023-02-04      A   36.650000
1     1000045     USA      F  1000045  2023-01-30      I   51.580000
2     1000071     USA      F  1000071  2023-02-02      I    6.710000
3     1000101     MEX      F  1000101  2023-02-05      A    5.674497
4     1000101     MEX      F  1000101  2023-02-02      A   18.130000
...       ...     ...    ...      ...         ...    ...         ...
2228  1049880     TUR      M  1049880  2023-01-26      I  186.690000
2229  1049891     BRA      F  1049891  2023-01-26      A   47.140000
2230  1049894     BRA      F  1049894  2023-01-25      I   34.050000
2231  1049927     AUS      F  1049927  2023-01-25      A   52.030000
2232  1049973     MEX      F  1049973  2023-01-31      A   85.930000

[2233 rows x 7 columns]

In [7]:
query5='''SELECT uid, COALESCE(activity.device, 'Unknown') AS device, COALESCE(activity.spent, 0 ) AS spent
FROM Activity;'''
read_query_function(query5)

<ipython-input-2-c09e6a76bd12>:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_frame = pd.read_sql_query(query,conn)

          uid device       spent
0     1000039      A   36.650000
1     1000045      I   51.580000
2     1000071      I    6.710000
3     1000101      A   18.130000
4     1000101      A    5.674497
...       ...    ...         ...
2228  1049880      I  186.690000
2229  1049891      A   47.140000
2230  1049894      I   34.050000
2231  1049927      A   52.030000
2232  1049973      A   85.930000

[2233 rows x 3 columns]

In [8]:
query6='''SELECT COUNT(DISTINCT uid) AS num_users_in_experiment
FROM activity;'''
read_query_function(query6)

<ipython-input-2-c09e6a76bd12>:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_frame = pd.read_sql_query(query,conn)

   num_users_in_experiment
0                     2094

In [9]:
query7='''WITH user_spend AS (
  SELECT
    uid,
    SUM(spent) AS total_spend,
    COUNT(*) as cnt_purchases
  FROM activity
  GROUP BY uid
),

joined AS (
  SELECT
    uid,
    gender,
    country,
    g.group as grp,
    CASE
      WHEN g.group = 'A' THEN 'control'
      WHEN g.group = 'B' THEN 'treatment'
      ELSE 'problem!'
    END AS cluster,
    CASE WHEN cnt_purchases > 0 THEN 1 ELSE 0 END AS converted
  FROM users
  LEFT JOIN groups g ON uid = id
  LEFT JOIN user_spend USING (uid)
)

SELECT
  SUM(converted) * 1.0 / COUNT(*) AS overall_conversion_rate
FROM joined;'''
read_query_function(query7)

<ipython-input-2-c09e6a76bd12>:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_frame = pd.read_sql_query(query,conn)

   overall_conversion_rate
0                 0.042784

In [10]:
query8='''WITH user_spend AS (
  SELECT
    uid,
    SUM(spent) AS total_spend,
    COUNT(*) as cnt_purchases
  FROM activity
  GROUP BY uid
),

joined AS (
  SELECT
    uid,
    gender,
    country,
    g.group as grp,
    CASE
      WHEN g.group = 'A' THEN 'control'
      WHEN g.group = 'B' THEN 'treatment'
      ELSE 'problem!'
    END AS cluster,
    CASE WHEN cnt_purchases > 0 THEN 1 ELSE 0 END AS converted
  FROM users
  LEFT JOIN groups g ON uid = id
  LEFT JOIN user_spend USING (uid)
)

SELECT
  cluster,
  COUNT(*) AS total_users,
  SUM(converted) AS converted_users,
  SUM(converted) * 1.0 / COUNT(*) AS conversion_rate
FROM joined
GROUP BY cluster;
'''
read_query_function(query8)

<ipython-input-2-c09e6a76bd12>:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_frame = pd.read_sql_query(query,conn)

     cluster  total_users  converted_users  conversion_rate
0    control        24343              955         0.039231
1  treatment        24600             1139         0.046301

In [11]:
query9='''WITH user_spend AS (
  SELECT
    uid,
    SUM(spent) AS total_spend,
    COUNT(*) as cnt_purchases
  FROM activity
  GROUP BY uid
),

joined AS (
  SELECT
    uid,gender, country,
    g.group as grp,
    CASE
      WHEN g.group = 'A' THEN 'control'
      WHEN g.group = 'B' THEN 'treatment'
      ELSE 'problem!'
    END AS cluster,
    CASE WHEN cnt_purchases > 0 THEN 1 ELSE 0 END AS converted,
    total_spend
  FROM users
  LEFT JOIN groups g ON uid = id
  LEFT JOIN user_spend USING (uid)
)

SELECT
  cluster,
  AVG(total_spend) AS avg_spend_per_user
FROM joined
GROUP BY cluster;
'''
read_query_function(query9)

<ipython-input-2-c09e6a76bd12>:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_frame = pd.read_sql_query(query,conn)

     cluster  avg_spend_per_user
0    control           86.016652
1  treatment           73.235581

In [ ]:

query10='''
WITH user_spend AS (
  SELECT
  	uid,
  	SUM(spent) AS total_spend,
		COUNT(*) as cnt_purchases
  FROM activity
  GROUP BY uid
),

joined AS (
  SELECT
    uid,
	  gender,
	  country,
    g.group as grp,
    CASE
  		WHEN g.group = 'A' THEN 'control'
  		WHEN g.group = 'B' THEN 'treatment'
  		ELSE 'problem!'
    END AS cluster,
    CASE WHEN cnt_purchases > 0 THEN 1 ELSE 0 END AS converted
  FROM users
  LEFT JOIN groups g ON uid = id
  LEFT JOIN user_spend USING (uid)
)

select *
from joined
'''
read_query_function(query10)

In [6]:
query11='''
WITH user_spend AS (
  SELECT  uid, SUM(spent) AS total_spend, COUNT(*) as cnt_purchases
  FROM activity
  GROUP BY uid
),
joined AS (
  SELECT
    uid,gender, country,
    g.group as grp,
    CASE
      WHEN g.group = 'A' THEN 'control'
      WHEN g.group = 'B' THEN 'treatment'
      ELSE 'problem!'
    END AS cluster,
    CASE WHEN cnt_purchases > 0 THEN 1 ELSE 0 END AS converted
  FROM users
  LEFT JOIN groups g ON uid = id
  LEFT JOIN user_spend USING (uid)
)

SELECT
  cluster,
  COUNT(*) AS total_users
FROM joined
GROUP BY cluster;
'''
read_query_function(query11)

<ipython-input-3-d1d0ad2996e6>:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_frame = pd.read_sql_query(query,conn)

     cluster  total_users
0    control        24343
1  treatment        24600

In [5]:
import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(_df_1, *['total_users'], **{})
chart